# Evaluating Model Performance

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (digits.data, digits.target, test_size = 0.3)

In [15]:
lr = LogisticRegression( max_iter = 5000)
lr.fit(X_train, y_train)
lr.score (X_test, y_test)

0.9629629629629629

In [16]:
params = lr.get_params()
print(params)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 5000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score (X_test, y_test)

0.9851851851851852

In [18]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

# K-Fold Cross Validation

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index, test_index in kf.split ([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score (model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [23]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [33]:
digits.target[train_index].flatten().shape

(1198,)

In [34]:
digits.target[test_index].flatten().shape

(599,)

In [43]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, digits.target[train_index].flatten(),\
                                     X_test, digits.target[test_index].flatten()))
    scores_svm.append(get_score(SVC(), X_train, digits.target[train_index].flatten(), X_test, digits.target[test_index].flatten()))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, digits.target[train_index].flatten(),\
                               X_test, digits.target[test_index].flatten()))

In [44]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [45]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [46]:
scores_rf

[0.9298831385642737, 0.9532554257095158, 0.9148580968280468]

In [47]:
np.average (scores_logistic)

0.9193099610461881

In [48]:
np.average (scores_svm)

0.9699499165275459

In [49]:
np.average (scores_rf)

0.9326655537006121

# cross_val_score function

The built in funtion for the above is the cross_val_score

In [51]:
from sklearn.model_selection import cross_val_score

In [52]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [53]:
cross_val_score(SVC(), digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92654424, 0.93155259, 0.92821369])

# Parameter Tuning

In [55]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8731378026070763

In [56]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9387988826815642

In [57]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9398944754810676

In [58]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9476784605834885