In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_actual = np.array([0.3,0.7,1,0,0.5])

In [3]:
# Mean Absolute Error = absolute(predicted value - actual value / n)
def mae(y_actual,y_predicted):
    total_error = 0
    for ya, yp in zip(y_actual, y_predicted):
        total_error += abs(yp - ya)
    print ("Total Error:", total_error)
    mae = round(total_error/ len (y_actual),2)
    print("Mean Absolute Error:", mae)
    return mae

In [4]:
mae(y_actual,y_predicted)

Total Error: 2.5
Mean Absolute Error: 0.5


0.5

In [5]:
np.abs(y_predicted-y_actual)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_actual))

0.5

Implementing Log Loss or Binary Cross Entropy

In [7]:
# Because we cannot calculate log 0 we need to replace the predicted values with values close to 0 amd 1
np.log([0])

C:\Users\nduku\AppData\Local\Temp\ipykernel_19304\818971425.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [8]:
epsilon = 1e-15

In [9]:
np.log([1e-15])

array([-34.53877639])

In [10]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [11]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [13]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [14]:
# Log Loss Formula
-np.mean(y_actual*np.log(y_predicted_new)+(1-y_actual)*np.log(1-y_predicted_new))

17.2696280766844

In [16]:
def log_loss(y_actual,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_actual*np.log(y_predicted_new)+(1-y_actual)*np.log(1-y_predicted_new))

In [17]:
log_loss(y_actual,y_predicted)

17.2696280766844

In [25]:
#Mean Squared Error
def mse(y_actual, y_predicted):
    total_error2 = 0
    for ya, yp in zip (y_actual, y_predicted):
        error = yp - ya
        total_error2 += error ** 2
    print ("Total Error:", total_error2)
    mse = total_error2 / len (y_actual)
    print("Mean Squared Error:", mse)
    return mse

In [26]:
mse(y_actual, y_predicted)

Total Error: 1.83
Mean Squared Error: 0.366


0.366

In [27]:
np.square(y_predicted-y_actual)

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [28]:
np.sum(np.square(y_predicted-y_actual))

1.83

In [29]:
np.mean(np.square(y_predicted-y_actual))

0.366