In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [15]:
one_hot("amazing restaurant", 50)

[11, 28]

In [16]:
vocab_size = 100
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[69, 8], [88, 38], [44, 83], [91, 63, 12], [9, 60, 47], [84, 8], [96, 60, 22], [93, 53], [93, 42], [54, 1]]


In [17]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[69  8  0  0]
 [88 38  0  0]
 [44 83  0  0]
 [91 63 12  0]
 [ 9 60 47  0]
 [84  8  0  0]
 [96 60 22  0]
 [93 53  0  0]
 [93 42  0  0]
 [54  1  0  0]]


In [18]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [19]:
X = padded_reviews
y = sentiment

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 4)              400       
                                                                 
 flatten_1 (Flatten)         (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 417 (1.63 KB)
Trainable params: 417 (1.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
model.fit(X, y, epochs=50, verbose=0)

In [22]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 133ms/step - loss: 0.6223 - accuracy: 1.0000


1.0

In [23]:
model.get_layer('embedding').get_weights()[0]

array([[-0.0004463 ,  0.09900297,  0.09511095, -0.09149058],
       [ 0.0300892 ,  0.04154168,  0.0261224 ,  0.00243846],
       [-0.01725351, -0.04280657, -0.00494163,  0.042667  ],
       [ 0.02350272, -0.01268629,  0.01075312,  0.0070583 ],
       [ 0.02458343, -0.01678367, -0.01280852,  0.00323368],
       [-0.02720656, -0.04889334, -0.00501806, -0.04036826],
       [-0.04064391, -0.03037015, -0.01370214, -0.04045729],
       [-0.01870284,  0.02311187,  0.0187901 ,  0.03198645],
       [-0.00479131, -0.03837265, -0.04143754, -0.02814415],
       [-0.01841052, -0.07434537, -0.03848707,  0.03904074],
       [ 0.028884  , -0.00281389, -0.02945143, -0.01672214],
       [-0.03617661, -0.04052702, -0.03515534,  0.00311672],
       [ 0.01823594, -0.03863623, -0.07589877,  0.06623337],
       [ 0.04915258, -0.0232065 , -0.04282874,  0.01167818],
       [-0.00325765, -0.01227885, -0.04441727, -0.04673822],
       [-0.04456153, -0.03834987, -0.00115632,  0.0132503 ],
       [ 0.03444434, -0.

In [24]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

100

In [25]:
weights[69]

array([-0.04577618, -0.10006361, -0.08745929,  0.09269416], dtype=float32)

In [26]:
weights[88]

array([-0.1016724 , -0.04989329, -0.09730409,  0.02483727], dtype=float32)